title: Funky Language
description: Documentation for the Funky functional language interpreter
theme: jekyll-theme-cayman
markdown: kramdown

github:
  repository_url: https://github.com/MAILabs-Edu-2026/funcpro-coursework-onditions